# GitHub Actions workflow for CI/CD pipeline
name: CI/CD Pipeline

# Trigger workflow on push or pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Define build job and checkout the repository
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
# Set up Python 3.13 environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
# Install Python dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
# Test job that runs after the build job
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
# Set up Python 3.13 environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
# Install Python dependencies from requirements.txt, including pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
# Run tests
      - name: Run tests
        run: echo "Skipping real database tests for CI/CD demo"
# Deploy job triggered on main branch after tests
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
# Trigger deployment on Render using stored secrets
      - name: Deploy to Render
        env:
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/v1/services/${SERVICE_ID}/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $API_KEY" \
            -d ''