name: CI/CD Pipeline

on:
  push:
    branches:
      - main        # run on pushes to main branch
  pull_request:
    branches:
      - main        # also run on PRs targeting main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13  # match your local environment

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code (optional)
        run: |
          pip install flake8
          flake8 .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            pytest tests/ --maxfail=1 --disable-warnings -q
          else
            echo "No tests directory found. Skipping tests."
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Triggering deploy on Render service $SERVICE_ID"
          curl -X POST "https://api.render.com/v1/services/${SERVICE_ID}/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $API_KEY" \
            -d ''